Add download speed and ETA
PojavLauncherTeam/PojavLauncher pull request #5685
Opened 2024-06-26 07:35 UTC by f401

2024-07-03 19:16 UTC, artdeell requested changes

2024-07-03 19:16 UTC, artdeell commented on app_pojavlauncher/src/main/java/net/kdt/pojavlaunch/Tools.java
> +    public static String trimSecondsToMiniutes(double seconds) {
Typo. Should be 'minutes'

2024-07-03 19:16 UTC, artdeell commented on app_pojavlauncher/src/main/java/net/kdt/pojavlaunch/Tools.java
> +            return (seconds / 60.0) + "min" + (seconds % 60.0) + "s";
Do not hardcode prefixes. Not all languages can understand "min" and "s" abbreviations

2024-07-03 19:16 UTC, artdeell commented on app_pojavlauncher/src/main/java/net/kdt/pojavlaunch/tasks/MinecraftDownloader.java
> +                // Using the number of files as a basis for progress bars is inaccurate
The file counter is used for the progress bar due to the fact that not all assets list their file size, like, for example, OptiFine. If you check its JSON, you will find that it only list a base URL and the library name for all of its libraries.

2024-07-03 19:16 UTC, artdeell commented on app_pojavlauncher/src/main/res/values/strings.xml
> +    <string name="newdl_downloading_game_files">Downloading at %.2f MB/s ETA: %s(%.2f MB/%.2f MB) </string>
Would this fit into a single line on a small screen?

2024-07-05 21:02 UTC, artdeell commented on app_pojavlauncher/src/main/java/net/kdt/pojavlaunch/tasks/MinecraftDownloader.java
> +                // Using the number of files as a basis for progress bars is inaccurate
The comment is not valid, still. The core statement in it is correct but it must be explained why we don't use size for the progress bar

2024-07-10 19:52 UTC, f401 commented
Delete remaining download time, keep speed.
Thank you for your patient guidance and explanation.I am also very sorry for any unnecessary trouble caused

2025-01-02 21:02 UTC, artdeell commented
Ended up implementing as part of #6428 
If you wish to add more, please open a new PR

2025-01-02 21:02 UTC, closed without merging